steps:
  # 1️⃣ Build Docker image using BuildKit for optimization
  - name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "DIRECTUS_URL is: '$$DIRECTUS_URL'"
        echo "REDIS_URL is: '$$REDIS_URL'"
        export DOCKER_BUILDKIT=1
        docker build \
          --build-arg DIRECTUS_URL=$$DIRECTUS_URL \
          --build-arg REDIS_URL=$$REDIS_URL \
          -t ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REGISTRY_REPO}/${_SERVICE_NAME}:$SHORT_SHA \
          -f Dockerfile .
    secretEnv: ['DIRECTUS_URL', 'REDIS_URL']

  # 2️⃣ Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REGISTRY_REPO}/${_SERVICE_NAME}:$SHORT_SHA'
      ]

  # 3️⃣ Deploy the new version to Cloud Run with environment variables
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        '${_SERVICE_NAME}',
        '--image',
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REGISTRY_REPO}/${_SERVICE_NAME}:$SHORT_SHA',
        '--region',
        '${_REGION}',
        '--platform',
        'managed',
        '--port=3000',
        '--allow-unauthenticated',
        '--set-env-vars=DIRECTUS_URL=$$DIRECTUS_URL,REDIS_URL=$$REDIS_URL',
        '${_MIN_INSTANCES}',
        '${_MAX_INSTANCES}'
      ]

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: '${_SERVICE_ACCOUNT}'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/UNTHAA_DIRECTUS_URL/versions/latest
      env: 'DIRECTUS_URL'
    - versionName: projects/$PROJECT_ID/secrets/UNTHAA_REDIS_URL/versions/latest
      env: 'REDIS_URL'
