export const ROUTES_WITHOUT_HEADER_AND_FOOTER = new Set([
  'login',
  'register',
  'change-password',
  'reset-password'
]);

export const LANGUAGE_TO_LOCALE_LANGUAGE: Record<string, string> = {
  en: 'en-US', // English (United States)
  ja: 'ja-JP', // Japanese (Japan)
  fr: 'fr-FR', // French (France)
  de: 'de-DE', // German (Germany)
  es: 'es-ES', // Spanish (Spain)
  pt: 'pt-PT', // Portuguese (Portugal)
  it: 'it-IT', // Italian (Italy)
  nl: 'nl-NL', // Dutch (Netherlands)
  ru: 'ru-RU', // Russian (Russia)
  zh: 'zh-CN', // Chinese (Simplified, China)
  ar: 'ar-SA', // Arabic (Saudi Arabia)
  ko: 'ko-KR', // Korean (South Korea)
  hi: 'hi-IN', // Hindi (India)
  bn: 'bn-IN', // Bengali (India)
  pl: 'pl-PL', // Polish (Poland)
  tr: 'tr-TR', // Turkish (Turkey)
  sv: 'sv-SE', // Swedish (Sweden)
  da: 'da-DK', // Danish (Denmark)
  no: 'no-NO', // Norwegian (Norway)
  fi: 'fi-FI', // Finnish (Finland)
  cs: 'cs-CZ', // Czech (Czech Republic)
  ro: 'ro-RO', // Romanian (Romania)
  hu: 'hu-HU', // Hungarian (Hungary)
  th: 'th-TH', // Thai (Thailand)
  vi: 'vi-VN', // Vietnamese (Vietnam)
  id: 'id-ID', // Indonesian (Indonesia)
  ms: 'ms-MY', // Malay (Malaysia)
  tl: 'tl-PH', // Filipino (Philippines)
  he: 'he-IL', // Hebrew (Israel)
  fa: 'fa-IR', // Persian (Iran)
  ur: 'ur-PK', // Urdu (Pakistan)
  sw: 'sw-KE', // Swahili (Kenya)
  sr: 'sr-RS', // Serbian (Serbia)
  mk: 'mk-MK', // Macedonian (North Macedonia)
  uk: 'uk-UA', // Ukrainian (Ukraine)
  lv: 'lv-LV', // Latvian (Latvia)
  et: 'et-EE', // Estonian (Estonia)
  lt: 'lt-LT', // Lithuanian (Lithuania)
  sq: 'sq-AL', // Albanian (Albania)
  bg: 'bg-BG', // Bulgarian (Bulgaria)
  hr: 'hr-HR', // Croatian (Croatia)
  sl: 'sl-SI', // Slovenian (Slovenia)
  sk: 'sk-SK', // Slovak (Slovakia)
  bs: 'bs-BA', // Bosnian (Bosnia and Herzegovina)
  am: 'am-ET', // Amharic (Ethiopia)
  hy: 'hy-AM', // Armenian (Armenia)
  ka: 'ka-GE', // Georgian (Georgia)
  rw: 'rw-RW', // Kinyarwanda (Rwanda)
  ne: 'ne-NP', // Nepali (Nepal)
  si: 'si-LK', // Sinhalese (Sri Lanka)
  km: 'km-KH', // Khmer (Cambodia)
  my: 'my-MM', // Burmese (Myanmar)
  lo: 'lo-LA', // Lao (Laos)
  mn: 'mn-MN', // Mongolian (Mongolia)
  bo: 'bo-CN', // Tibetan (China)
  ps: 'ps-AF', // Pashto (Afghanistan)
  cy: 'cy-GB', // Welsh (United Kingdom)
  eu: 'eu-ES', // Basque (Spain)
  gl: 'gl-ES', // Galician (Spain)
  is: 'is-IS', // Icelandic (Iceland)
  jw: 'jw-ID', // Javanese (Indonesia)
  mr: 'mr-IN', // Marathi (India)
  ta: 'ta-IN', // Tamil (India)
  te: 'te-IN', // Telugu (India)
  kn: 'kn-IN', // Kannada (India)
  gu: 'gu-IN', // Gujarati (India)
  pa: 'pa-IN', // Punjabi (India)
  ml: 'ml-IN', // Malayalam (India)
  or: 'or-IN', // Oriya (India)
  as: 'as-IN', // Assamese (India)
  bh: 'bh-IN', // Bihari (India)
  qu: 'qu-PE', // Quechua (Peru)
  dz: 'dz-BT' // Dzongkha (Bhutan)
};

export const LOCALE_TO_LANGUAGE: Record<string, string> = {
  'en-US': 'en', // English (United States)
  'en-GB': 'en', // English (United Kingdom)
  'ja-JP': 'ja', // Japanese (Japan)
  'fr-FR': 'fr', // French (France)
  'de-DE': 'de', // German (Germany)
  'es-ES': 'es', // Spanish (Spain)
  'pt-PT': 'pt', // Portuguese (Portugal)
  'it-IT': 'it', // Italian (Italy)
  'nl-NL': 'nl', // Dutch (Netherlands)
  'ru-RU': 'ru', // Russian (Russia)
  'zh-CN': 'zh', // Chinese (Simplified, China)
  'ar-SA': 'ar', // Arabic (Saudi Arabia)
  'ko-KR': 'ko', // Korean (South Korea)
  'hi-IN': 'hi', // Hindi (India)
  'bn-IN': 'bn', // Bengali (India)
  'pl-PL': 'pl', // Polish (Poland)
  'tr-TR': 'tr', // Turkish (Turkey)
  'sv-SE': 'sv', // Swedish (Sweden)
  'da-DK': 'da', // Danish (Denmark)
  'no-NO': 'no', // Norwegian (Norway)
  'fi-FI': 'fi', // Finnish (Finland)
  'cs-CZ': 'cs', // Czech (Czech Republic)
  'ro-RO': 'ro', // Romanian (Romania)
  'hu-HU': 'hu', // Hungarian (Hungary)
  'th-TH': 'th', // Thai (Thailand)
  'vi-VN': 'vi', // Vietnamese (Vietnam)
  'id-ID': 'id', // Indonesian (Indonesia)
  'ms-MY': 'ms', // Malay (Malaysia)
  'tl-PH': 'tl', // Filipino (Philippines)
  'he-IL': 'he', // Hebrew (Israel)
  'fa-IR': 'fa', // Persian (Iran)
  'ur-PK': 'ur', // Urdu (Pakistan)
  'sw-KE': 'sw', // Swahili (Kenya)
  'sr-RS': 'sr', // Serbian (Serbia)
  'mk-MK': 'mk', // Macedonian (North Macedonia)
  'uk-UA': 'uk', // Ukrainian (Ukraine)
  'lv-LV': 'lv', // Latvian (Latvia)
  'et-EE': 'et', // Estonian (Estonia)
  'lt-LT': 'lt', // Lithuanian (Lithuania)
  'sq-AL': 'sq', // Albanian (Albania)
  'bg-BG': 'bg', // Bulgarian (Bulgaria)
  'hr-HR': 'hr', // Croatian (Croatia)
  'sl-SI': 'sl', // Slovenian (Slovenia)
  'sk-SK': 'sk', // Slovak (Slovakia)
  'bs-BA': 'bs', // Bosnian (Bosnia and Herzegovina)
  'am-ET': 'am', // Amharic (Ethiopia)
  'hy-AM': 'hy', // Armenian (Armenia)
  'ka-GE': 'ka', // Georgian (Georgia)
  'rw-RW': 'rw', // Kinyarwanda (Rwanda)
  'ne-NP': 'ne', // Nepali (Nepal)
  'si-LK': 'si', // Sinhalese (Sri Lanka)
  'km-KH': 'km', // Khmer (Cambodia)
  'my-MM': 'my', // Burmese (Myanmar)
  'lo-LA': 'lo', // Lao (Laos)
  'dz-BT': 'dz', // Dzongkha (Bhutan)
  'mn-MN': 'mn', // Mongolian (Mongolia)
  'bo-CN': 'bo', // Tibetan (China)
  'ps-AF': 'ps', // Pashto (Afghanistan)
  'cy-GB': 'cy', // Welsh (United Kingdom)
  'eu-ES': 'eu', // Basque (Spain)
  'gl-ES': 'gl', // Galician (Spain)
  'is-IS': 'is', // Icelandic (Iceland)
  'jw-ID': 'jw', // Javanese (Indonesia)
  'mr-IN': 'mr', // Marathi (India)
  'ta-IN': 'ta', // Tamil (India)
  'te-IN': 'te', // Telugu (India)
  'kn-IN': 'kn', // Kannada (India)
  'gu-IN': 'gu', // Gujarati (India)
  'pa-IN': 'pa', // Punjabi (India)
  'ml-IN': 'ml', // Malayalam (India)
  'or-IN': 'or', // Oriya (India)
  'as-IN': 'as', // Assamese (India)
  'bh-IN': 'bh', // Bihari (India)
  'qu-PE': 'qu' // Quechua (Peru)
};

export const LOCALE_TO_CURRENCY: Record<string, string> = {
  'en-US': 'USD',
  'fr-FR': 'EUR',
  'de-DE': 'EUR',
  'ja-JP': 'JPY',
  'es-ES': 'EUR',
  'it-IT': 'EUR',
  'pt-BR': 'BRL',
  'ru-RU': 'RUB'
};

export const PARAMS = {
  PRODUCT_ID: 'product-id',
  IMAGE_SET: 'image-set'
};
